name: 'dbt_nyc_mvc'
version: '1.0.0'
config-version: 2

profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# These settings can be overridden in the individual model files using the `{{ config(...) }}` macro.
models:
  dbt_nyc_mvc:
    staging:
      materialized: view
    core:
      materialized: table
